services:
  mc:
    image: itzg/minecraft-server:java21
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        echo "--- [Coolify] Erstelle Auto-Install Script für Chunky & Spark ---"
        mkdir -p /scripts
        
        # Wir schreiben den Inhalt des Skripts direkt in eine Datei im Container
        echo '#!/bin/bash' > /scripts/99-install-extras.sh
        echo 'echo "--- [Extra-Mods] Lade Chunky und Spark herunter... ---"' >> /scripts/99-install-extras.sh
        echo '/usr/bin/mc-image-helper curseforge install --api-key $CF_API_KEY --minecraft-version 1.21.1 --mod-loader neoforge --output-directory /data/mods chunky spark' >> /scripts/99-install-extras.sh
        
        chmod +x /scripts/99-install-extras.sh
        
        # Übergebe die Kontrolle an den normalen Server-Start
        exec /start
    environment:
      SEED: "-123456793079414942"
      TYPE: AUTO_CURSEFORGE
      environment:
      JVM_OPTS: "-Xmx10G -Xms10G -XX:+UseZGC -XX:+ZGenerational -XX:+AlwaysPreTouch"
      CF_PAGE_URL: ${CF_PAGE_URL}
      CF_API_KEY: ${CF_API_KEY}
      MOTD: |-
        §1§lFurz24.de
        §7powered by §6henk.pm
      ALLOW_FLIGHT: TRUE
      OPS: |
        Zurki
      VERSION: 1.21.1
      EULA: "true"
      CF_EXCLUDE_MODS: "forgeskyboxes,colorwheel"
      CF_FORCE_SYNCHRONIZE: "false"
    ports:
      - "25575:25575"
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12g
          cpus: "10"

volumes:
  data: {}
