services:
  mc:
    image: itzg/minecraft-server:java21
    environment:
      TYPE: AUTO_CURSEFORGE
      MEMORY: "10G"
      JVM_OPTS: "-XX:+UseZGC -XX:+ZGenerational -XX:+AlwaysPreTouch"
      CF_PAGE_URL: ${CF_PAGE_URL}
      CF_API_KEY: ${CF_API_KEY}
      OPS: |
        Zurki
      VERSION: 1.21.1
      EULA: "true"
      CF_EXCLUDE_MODS: "forgeskyboxes,colorwheel"
      CURSEFORGE_FILES: "chunky-pregenerator-forge,spark,ai-improvements,styled-chat-unofficial-neoforge"
      CF_FORCE_SYNCHRONIZE: "false"

      #MC Settings
      SIMULATION_DISTANCE: "5"
      MAX_TICK_TIME: "60000"
      ALLOW_FLIGHT: "TRUE" # Besser in Anführungszeichen
      MAX_PLAYERS: 99999
      SEED: "-123456793079414942"
      MOTD: |-
        §3§l§k|||§r§5Hallo Nina, Mori, Svenni, Hagen, Paul§3§l§k|||§r
        §7powered by 🐹§6Hamsterrädern§r🐹
    ports:
      - "25575:25575"
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12g
          cpus: "10"

volumes:
  data: {}
